name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php: 8.1
            phpunit: ^10.0
          - php: 8.2
            phpunit: ^11.0
          - php: 8.3
            phpunit: ^12.0
          - php: 8.4
            phpunit: ^12.0

    name: PHP ${{ matrix.php }} Test

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit
          extensions: mbstring, xml, ctype, json, curl
          coverage: none

      - name: Install dependencies
        run: |
          composer require --dev phpunit/phpunit "${{ matrix.phpunit }}" --with-all-dependencies
          composer install --no-progress --prefer-dist

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
